version: "3.9"

services:
  komari:
    image: ghcr.io/komari-backup/komari:latest
    container_name: komari
    restart: unless-stopped
    ports:
      - "25774:25774"
    environment:
      - KOMARI_DB_TYPE=sqlite
      - KOMARI_DB_FILE=/opt/komari/data/komari.db
      - KOMARI_LISTEN=0.0.0.0:25774
      - GH_BACKUP_USER=your_github_username
      - GH_REPO=your_private_repo_name
      - GH_PAT=your_github_personal_access_token
      - GH_EMAIL=your_github_email@example.com
    volumes:
      - ./data:/app/data
